import React, { useState } from 'react';
import { aiEvaluateCode, aiGenerateQuestion, aiInterviewReport } from '../services/api';
export default function AgentsPage() {
  const [tab, setTab] = useState('evaluate'); const [loading, setLoading] = useState(false); const [result, setResult] = useState(null);
  const [inputs, setInputs] = useState({ code: 'function twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) return [map.get(complement), i];\n    map.set(nums[i], i);\n  }\n  return [];\n}', question: 'Two Sum - Find two numbers that add up to target', language: 'javascript',
    difficulty: 'medium', category: 'arrays', skills: 'problem solving, data structures',
    candidate_name: 'Alice Chen', level: 'senior', scores: '{"algorithms": 8.5, "system_design": 9.0, "code_quality": 8.0}', questions_summary: 'Two Sum (easy), LRU Cache (medium), System Design URL Shortener (hard)' });
  const renderResult = (obj, depth = 0) => {
    if (!obj) return null; if (typeof obj === 'string') return <p style={{ color: '#e0e0e0', lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>{obj}</p>;
    if (Array.isArray(obj)) return <div style={{ marginLeft: depth * 12 }}>{obj.map((item, i) => <div key={i} style={{ background: '#1a1a2e', padding: 12, borderRadius: 8, marginBottom: 8, borderLeft: '3px solid #e94560' }}>{typeof item === 'object' ? renderResult(item, depth + 1) : <span style={{ color: '#e0e0e0' }}>{String(item)}</span>}</div>)}</div>;
    return <div style={{ marginLeft: depth * 12 }}>{Object.entries(obj).map(([k, v]) => <div key={k} style={{ marginBottom: 12 }}><div style={{ color: '#e94560', fontSize: 13, fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 4 }}>{k.replace(/_/g, ' ')}</div>{typeof v === 'object' && v !== null ? renderResult(v, depth + 1) : <div style={{ color: '#e0e0e0', background: '#1a1a2e', padding: '8px 12px', borderRadius: 6 }}>{typeof v === 'number' ? <span style={{ color: '#2ecc71', fontWeight: 'bold', fontSize: 18 }}>{v}</span> : typeof v === 'boolean' ? <span style={{ color: v ? '#2ecc71' : '#e94560', fontWeight: 'bold' }}>{v ? 'Yes' : 'No'}</span> : String(v)}</div>}</div>)}</div>;
  };
  const run = async () => { setLoading(true); setResult(null); try { let r; if (tab === 'evaluate') r = await aiEvaluateCode({ code: inputs.code, question: inputs.question, language: inputs.language }); else if (tab === 'generate') r = await aiGenerateQuestion({ difficulty: inputs.difficulty, category: inputs.category, skills: inputs.skills }); else r = await aiInterviewReport({ candidate_name: inputs.candidate_name, level: inputs.level, scores: inputs.scores, questions_summary: inputs.questions_summary }); setResult(r); } catch { setResult({ error: 'Failed' }); } setLoading(false); };
  const tabs = [{key:'evaluate',label:'📝 Evaluate Code'},{key:'generate',label:'🎲 Generate Question'},{key:'report',label:'📊 Interview Report'}];
  return (<div><h1 style={{ color: '#fff', marginBottom: 20 }}>AI Interview Agents</h1>
    <div style={{ display: 'flex', gap: 8, marginBottom: 24 }}>{tabs.map(t => (<button key={t.key} onClick={() => { setTab(t.key); setResult(null); }} style={{ padding: '10px 20px', background: tab === t.key ? '#e94560' : '#16213e', color: tab === t.key ? '#fff' : '#ccc', border: '1px solid #0f3460', borderRadius: 8, cursor: 'pointer' }}>{t.label}</button>))}</div>
    <div style={{ background: '#16213e', padding: 24, borderRadius: 12, marginBottom: 20 }}>
      {tab === 'evaluate' && <><div style={{marginBottom:12}}><label style={{color:'#ccc',fontSize:13}}>Question</label><input value={inputs.question} onChange={e=>setInputs({...inputs,question:e.target.value})} style={{width:'100%',padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff',marginTop:4,boxSizing:'border-box'}} /></div>
        <div style={{marginBottom:12}}><label style={{color:'#ccc',fontSize:13}}>Code</label><textarea value={inputs.code} onChange={e=>setInputs({...inputs,code:e.target.value})} rows={8} style={{width:'100%',padding:12,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#2ecc71',fontFamily:'monospace',fontSize:13,marginTop:4,resize:'vertical',boxSizing:'border-box'}} /></div>
        <select value={inputs.language} onChange={e=>setInputs({...inputs,language:e.target.value})} style={{padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff'}}>{['javascript','python','java','go','rust','typescript'].map(l=><option key={l}>{l}</option>)}</select></>}
      {tab === 'generate' && <>{[{k:'skills',l:'Skills to Test'}].map(f => (<div key={f.k} style={{marginBottom:12}}><label style={{color:'#ccc',fontSize:13}}>{f.l}</label><input value={inputs[f.k]} onChange={e=>setInputs({...inputs,[f.k]:e.target.value})} style={{width:'100%',padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff',marginTop:4,boxSizing:'border-box'}} /></div>))}
        <div style={{display:'flex',gap:12}}><select value={inputs.difficulty} onChange={e=>setInputs({...inputs,difficulty:e.target.value})} style={{padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff'}}>{['easy','medium','hard'].map(d=><option key={d}>{d}</option>)}</select>
        <select value={inputs.category} onChange={e=>setInputs({...inputs,category:e.target.value})} style={{padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff'}}>{['arrays','strings','trees','graphs','dynamic_programming','design','system_design'].map(c=><option key={c} value={c}>{c.replace(/_/g,' ')}</option>)}</select></div></>}
      {tab === 'report' && <>{[{k:'candidate_name',l:'Candidate Name'},{k:'level',l:'Level'},{k:'scores',l:'Scores (JSON)'},{k:'questions_summary',l:'Questions Summary'}].map(f => (<div key={f.k} style={{marginBottom:12}}><label style={{color:'#ccc',fontSize:13}}>{f.l}</label><input value={inputs[f.k]} onChange={e=>setInputs({...inputs,[f.k]:e.target.value})} style={{width:'100%',padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff',marginTop:4,boxSizing:'border-box'}} /></div>))}</>}
      <button onClick={run} disabled={loading} style={{ padding: '12px 30px', background: loading ? '#888' : '#e94560', color: '#fff', border: 'none', borderRadius: 6, cursor: loading ? 'not-allowed' : 'pointer', marginTop: 12 }}>{loading ? '⏳ Processing...' : '🚀 Run AI'}</button>
    </div>
    {result && <div style={{ background: '#16213e', padding: 24, borderRadius: 12 }}><h3 style={{ color: '#e94560', marginTop: 0 }}>Results</h3>{renderResult(result)}</div>}
  </div>);
}
